//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgcode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pgcode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*build: 2019-11-16 18:18:45:771, version: 1*/
        ///(function(){&quot;use strict&quot;;const e=this;&quot;object&quot;==typeof global&amp;&amp;global;var t;!function(t){t.global=e;class i{constructor(){this._detected=!1,this._isWindows=!1,this._isWebWorker=!1}get isWindows(){return this._detect(),this._isWindows}get isWebWorker(){return this._detect(),this._isWebWorker}_detect(){this._detected||(this._detected=!0,this._isWindows=i._isWindows(),this._isWebWorker=&quot;function&quot;==typeof t.global.importScripts)}static _isWindows(){return!!(&quot;undefi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _app_index_js {
            get {
                return ResourceManager.GetString("/app/index.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html{font-family:&apos;Consolas&apos;, &apos;Courier New&apos;, &apos;monospace&apos;;font-size:12px;line-height:1.15}body{margin:0;color:#C5C5C5;background-color:#1E1E1E}#loading{position:absolute;left:0px;top:0px;width:100%;height:100%;justify-content:center;align-content:center;display:grid;font-size:10em;text-align:center}#app{position:absolute;left:0px;top:0px;width:100%;height:100%;z-index:-1;overflow:hidden;display:grid;grid-template-columns:50px 250px 3px auto;grid-template-rows:auto 20px;grid-template-areas:&apos;toolbar side-panel  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _css_theme_dark_css {
            get {
                return ResourceManager.GetString("/css/theme-dark.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html{font-family:&apos;Consolas&apos;, &apos;Courier New&apos;, &apos;monospace&apos;;font-size:12px;line-height:1.15}body{margin:0;color:#1E1E1E;background-color:#C5C5C5}#loading{position:absolute;left:0px;top:0px;width:100%;height:100%;justify-content:center;align-content:center;display:grid;font-size:10em;text-align:center}#app{position:absolute;left:0px;top:0px;width:100%;height:100%;z-index:-1;overflow:hidden;display:grid;grid-template-columns:50px 250px 3px auto;grid-template-rows:auto 20px;grid-template-areas:&apos;toolbar side-panel  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _css_theme_light_css {
            get {
                return ResourceManager.GetString("/css/theme-light.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _favicon_ico {
            get {
                object obj = ResourceManager.GetObject("/favicon.ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _fonts_icons_woff2 {
            get {
                object obj = ResourceManager.GetObject("/fonts/icons.woff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link rel=&quot;icon&quot; type=&quot;image/x-icon&quot; href=&quot;favicon.ico?v=1&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; id=&quot;theme&quot; type=&quot;text/css&quot; href=&quot;css/theme-dark.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;loading&quot;&gt;
        ///        &amp;#8987;
        ///        &lt;script&gt;
        ///            setTimeout(function() { var e = document.getElementById(&quot;loading&quot;); if (e) e.innerHTML = &quot;Please update to modern browser!&quot;; }, 3000);
        ///            window.require = {paths: {&apos;vs&apos;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _index_html {
            get {
                return ResourceManager.GetString("/index.html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!-----------------------------------------------------------
        /// * Copyright (c) Microsoft Corporation. All rights reserved.
        /// * Version: 0.18.1(d7a26172c5955d29d2a8cca4377b53b28925c766)
        /// * Released under the MIT license
        /// * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
        /// *-----------------------------------------------------------*/
        ///(function(){
        ///var e=[&quot;require&quot;,&quot;exports&quot;,&quot;vs/editor/common/core/position&quot;,&quot;vs/base/common/platform&quot;,&quot;vs/editor/common/core/uint&quot;,&quot;vs/base/common/errors&quot;,&quot;vs/editor/com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _libs_monaco_editor_min_vs_base_worker_workerMain_js {
            get {
                return ResourceManager.GetString("/libs/monaco-editor/min/vs/base/worker/workerMain.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!-----------------------------------------------------------------------------
        /// * Copyright (c) Microsoft Corporation. All rights reserved.
        /// * monaco-languages version: 1.8.0(0ed9a6c3e90a24375fab54f7205fb76ce992f117)
        /// * Released under the MIT license
        /// * https://github.com/Microsoft/monaco-languages/blob/master/LICENSE.md
        /// *-----------------------------------------------------------------------------*/
        ///define(&quot;vs/basic-languages/pgsql/pgsql&quot;,[&quot;require&quot;,&quot;exports&quot;],function(_,e){&quot;use strict&quot;;Object.definePro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _libs_monaco_editor_min_vs_basic_languages_pgsql_pgsql_js {
            get {
                return ResourceManager.GetString("/libs/monaco-editor/min/vs/basic-languages/pgsql/pgsql.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!-----------------------------------------------------------
        /// * Copyright (c) Microsoft Corporation. All rights reserved.
        /// * Version: 0.18.1(d7a26172c5955d29d2a8cca4377b53b28925c766)
        /// * Released under the MIT license
        /// * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
        /// *-----------------------------------------------------------*/.monaco-action-bar{text-align:right;overflow:hidden;white-space:nowrap}.monaco-action-bar .actions-container{display:flex;margin:0 auto;padding:0;width:100%;justify-co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _libs_monaco_editor_min_vs_editor_editor_main_css {
            get {
                return ResourceManager.GetString("/libs/monaco-editor/min/vs/editor/editor.main.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!-----------------------------------------------------------
        /// * Copyright (c) Microsoft Corporation. All rights reserved.
        /// * Version: 0.18.1(d7a26172c5955d29d2a8cca4377b53b28925c766)
        /// * Released under the MIT license
        /// * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
        /// *-----------------------------------------------------------*/
        ///(function(){
        ///var e,t=[&quot;exports&quot;,&quot;require&quot;,&quot;vs/base/common/lifecycle&quot;,&quot;vs/editor/common/core/range&quot;,&quot;vs/base/common/event&quot;,&quot;vs/base/common/strings&quot;,&quot;vs/nls&quot;,&quot;vs/nls!vs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _libs_monaco_editor_min_vs_editor_editor_main_js {
            get {
                return ResourceManager.GetString("/libs/monaco-editor/min/vs/editor/editor.main.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!-----------------------------------------------------------
        /// * Copyright (c) Microsoft Corporation. All rights reserved.
        /// * Version: 0.18.1(d7a26172c5955d29d2a8cca4377b53b28925c766)
        /// * Released under the MIT license
        /// * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
        /// *-----------------------------------------------------------*/
        ///define(&quot;vs/editor/editor.main.nls&quot;,{&quot;vs/base/browser/ui/actionbar/actionbar&quot;:[&quot;{0} ({1})&quot;],&quot;vs/base/browser/ui/aria/aria&quot;:[&quot;{0} (occurred again)&quot;,&quot;{0} (occurred {1} t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _libs_monaco_editor_min_vs_editor_editor_main_nls_js {
            get {
                return ResourceManager.GetString("/libs/monaco-editor/min/vs/editor/editor.main.nls.js", resourceCulture);
            }
        }
    }
}
